version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "06:00"
    timezone: "Asia/Kolkata"
  labels:
    - "dependencies"
  open-pull-requests-limit: 20
  ignore:
    - dependency-name: "python-telegram-bot"
    # Ignoring all ptb updates
    - dependency-name: "aiohttp"
    # Ignoring all aiohttp updates
    - dependency-name: "emoji"
    # Removed get_regexp method in update
